version: "3.9"
services:
  web:
    build: .
    command: python /src/manage.py runserver 0.0.0.0:8000
    # command: gunicorn config.wsgi -b 0.0.0.0:8000 
    volumes:
      - .:/src
    ports:
      - 8000:8000
    depends_on:
      - db 
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-j9!#p667t+kh_)9zqs3_e3*7#1hdgx7blwfqgfx&hbs$$!@%r^a"
      - "DJANGO_DEBUG=True"
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data:
